import os
import re
from typing import Dict, List, Set

from api.v1.helpers.forge_helpers import run_command, write_remappings
from common import logger


def find_import_paths(repo_dir: str) -> Set[str]:
    """
    Scans Solidity files to find all external import paths.

    Args:
        repo_dir (str): The repository directory.

    Returns:
        Set[str]: A set of external import paths.
    """
    import_paths = set()
    for root, _, files in os.walk(repo_dir):
        for file in files:
            if file.endswith(".sol"):
                with open(os.path.join(root, file), "r", encoding="utf-8") as f:
                    content = f.read()
                    imports = re.findall(r'import\s+["\']([^"\']+)["\'];', content)
                    for imp in imports:
                        if not imp.startswith("."):
                            # Collect the full import path
                            import_paths.add(imp)
    return import_paths


async def generate_and_write_remappings(
    temp_dir: str, custom_remappings: Dict[str, Dict[str, str]]
) -> List[str]:
    remappings = []

    for import_path, data in custom_remappings.items():
        folder_name = data["folder_name"]
        remappings.append(f"{import_path}=lib/{folder_name}/")

    # Remove duplicates while preserving order
    remappings = list(dict.fromkeys(remappings))

    logger.info(f"Remappings generated: {remappings}")

    # Write remappings to file
    await write_remappings(temp_dir, remappings)
    logger.info("Remappings written successfully")

    return remappings


async def generate_remappings_with_foundry(temp_dir: str) -> List[str]:
    """
    Generates remappings using Foundry's 'forge remappings' command and writes them to remappings.txt.

    Args:
        temp_dir (str): The temporary directory where the project is located.

    Returns:
        List[str]: A list of remapping strings.
    """
    logger.info("Generating remappings with Foundry...")
    returncode, stdout, stderr = await run_command(["forge", "remappings"], cwd=temp_dir)
    if returncode != 0:
        # logger.error(f"Failed to generate remappings with Foundry: {stderr}")
        raise ValueError(f"Failed to generate remappings with Foundry: {stderr}")

    remappings = stdout.strip().splitlines()
    if not remappings:
        raise ValueError("No remappings were generated by Foundry.")

    logger.info(f"Remappings generated: {remappings}")

    # Write remappings to file
    await write_remappings(temp_dir, remappings)
    logger.info("Remappings written successfully using Foundry")

    return remappings
