# Use the Node.js 18 LTS version as the base image
FROM node:18.19.0-slim

# Define build arguments - only for variables needed at build time (prefixed with NEXT_PUBLIC_)
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_GITHUB_APP_URL

# Set public environment variables needed at build time (prefixed with NEXT_PUBLIC_)
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_GITHUB_APP_URL=${NEXT_PUBLIC_GITHUB_APP_URL}

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json into the container
COPY package*.json ./

# Install the Node.js dependencies
RUN npm install

# Copy the rest of your application code into the container
COPY . .

# Build the application and install Nginx
RUN npm run build && \
    apt-get update && \
    apt-get install -y nginx apache2-utils && \
    rm -rf /var/lib/apt/lists/*

# Copy the Nginx configuration file with auth enabled
COPY nginx.staging.conf /etc/nginx/nginx.conf

# Copy the .htpasswd file for basic authentication
COPY .htpasswd /etc/nginx/.htpasswd

# Expose the port Nginx will use
EXPOSE 80

# Start the Node.js app and Nginx
CMD ["sh", "-c", "npm start & nginx -g 'daemon off;'"]
