# Use a specific Node.js version instead of the LTS tag
FROM node:18.19.0-slim

# Set the working directory inside the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json into the working directory
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the frontend application files into the working directory
COPY frontend .

# Build the Next.js application
RUN npm run build

# Expose the default Next.js port
EXPOSE 3000

# Command to run the production build
CMD ["npm", "start"]
