# Use the official Python image from the Docker Hub
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Install Nginx and necessary packages for setting up basic authentication
RUN apt-get update && apt-get install -y nginx apache2-utils && rm -rf /var/lib/apt/lists/*

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the .htpasswd file for basic auth
COPY .htpasswd /etc/nginx/.htpasswd

# Expose the port that Nginx will run on
EXPOSE 80

# Run App and Nginx
CMD npm run dev & nginx -g 'daemon off;'
