# For Docker local testing only
# TODO: 
# - Create a new .env.staging file in backend/
# - Change the frontend url to: http://localhost:8080
services:
  backend-staging:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.staging
    container_name: backend-staging
    ports:
      - "8000:8000"
    networks:
      - auditor-staging-network
    env_file:
      - ./backend/.env.staging
    environment:
      - NODE_ENV=staging

  frontend-staging:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend.staging
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
        - NEXT_PUBLIC_GITHUB_APP_URL=https://github.com/apps/auditagent-dev/installations/new

    container_name: frontend-staging
    ports:
      - "8080:80"  # Using 8080 to avoid conflicts with dev environment
    networks:
      - auditor-staging-network
    env_file:
      - ./frontend/.env
    depends_on:
      - backend-staging

networks:
  auditor-staging-network:
    driver: bridge 