# Build stage
FROM python:3.12.0-slim AS builder

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1

# Install build dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    gnupg \
    build-essential \
    libssl-dev \
    wget \
    && curl -L https://foundry.paradigm.xyz | bash \
    && /root/.foundry/bin/foundryup \
    && curl -s https://packages.stripe.dev/api/security/keypair/stripe-cli-gpg/public | gpg --dearmor | tee /usr/share/keyrings/stripe.gpg > /dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/stripe.gpg] https://packages.stripe.dev/stripe-cli-debian-local stable main" | tee -a /etc/apt/sources.list.d/stripe.list \
    && apt-get update && apt-get install -y stripe \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Final stage
FROM python:3.12.0-slim

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PATH="/root/.foundry/bin:${PATH}"

# Copy installed tools from builder stage
COPY --from=builder /root/.foundry /root/.foundry
COPY --from=builder /usr/local/bin/stripe /usr/local/bin/stripe

# Install runtime dependencies including Node.js and npm
RUN apt-get update && apt-get install -y \
    curl \
    git \
    build-essential \
    libssl-dev \
    apt-transport-https \
    ca-certificates \
    gnupg \
    redis-server \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs=18.* \
    && npm install -g npm@latest \
    # Install Doppler
    && curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | gpg --dearmor -o /usr/share/keyrings/doppler-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main" | tee /etc/apt/sources.list.d/doppler-cli.list \
    && apt-get update && apt-get install -y doppler \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/backend

# Copy and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir toml==0.10.2 slither-analyzer==0.10.0 solc-select==1.0.4

# Install playwright and its dependencies
RUN playwright install && playwright install-deps

# Copy the rest of your application code
COPY . .

EXPOSE 8000

# Start Redis and run the application with Doppler
CMD redis-server --daemonize yes && \
    redis-cli ping && \
    doppler run -- python3 main.py 