# Build stage
FROM ubuntu:24.04 AS builder

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1

# Install build dependencies, Foundry and Stripe CLI
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    curl \
    git \
    gnupg \
    wget \
    xz-utils \
    # Install Foundry
    && curl --proto "=https" -L https://foundry.paradigm.xyz | bash \
    && /root/.foundry/bin/foundryup \
    # Install Aderyn
    && curl --proto '=https' --tlsv1.2 -LsSf https://github.com/cyfrin/aderyn/releases/download/aderyn-v0.4.2/aderyn-installer.sh | sh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Final stage
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PATH="/root/.foundry/bin:/root/.cargo/bin:${PATH}"

# Copy installed tools from builder stage
COPY --from=builder /root/.foundry /root/.foundry
COPY --from=builder /root/.cargo /root/.cargo

# Install only runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    python3 \
    python3-pip \
    python3-venv \
    # Install Node.js
    && curl --proto "=https" --tlsv1.2 -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y --no-install-recommends nodejs=20.* \
    && npm install -g --ignore-scripts npm@latest \
    # Install Doppler
    && curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | gpg --dearmor -o /usr/share/keyrings/doppler-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main" | tee /etc/apt/sources.list.d/doppler-cli.list \
    && apt-get update && apt-get --no-install-recommends install -y doppler \
    # Clean up
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /root/.npm/* /root/.cache/*

# Create and activate virtual environment
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install Python dependencies in virtual environment
WORKDIR /app/backend
COPY requirements.txt .

RUN pip install --no-cache-dir setuptools wheel \
    && pip install --no-cache-dir -r requirements.txt \
    && playwright install chromium --with-deps --only-shell \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /root/.npm/*

# Copy application code
COPY api ./api
COPY config ./config
COPY core ./core
COPY main.py .

EXPOSE 8000

# Start the application with Doppler
CMD ["sh", "-c", "doppler run -- python3 main.py"]
