SLITHER_DETECTOR_MAP = {
    "abiencoderv2-array": "Unsafe Storage Array Encoding",
    "arbitrary-send-erc20": "Unauthorized ERC20 Token Transfer",
    "array-by-reference": "Unintended Storage Array Modification",
    "encode-packed-collision": "ABI Encoding Collision Risk",
    "incorrect-shift": "Incorrect Bit Shift Operation",
    "multiple-constructors": "Multiple Constructor Definitions",
    "name-reused": "Duplicate Contract Name",
    "protected-vars": "Unprotected Critical Variables",
    "public-mappings-nested": "Exposed Nested Mapping Data",
    "rtlo": "Malicious Unicode Character Usage",
    "shadowing-state": "State Variable Shadowing",
    "suicidal": "Unprotected Contract Self-Destruct",
    "uninitialized-state": "Uninitialized State Variables",
    "uninitialized-storage": "Uninitialized Storage Variables",
    "unprotected-upgrade": "Unprotected Upgradeable Contract",
    "codex": "AI-Detected Vulnerability",
    "arbitrary-send-erc20-permit": "Unauthorized ERC20 Transfer with Permit",
    "arbitrary-send-eth": "Arbitrary Ether Sending",
    "controlled-array-length": "Manipulated Array Length",
    "controlled-delegatecall": "Controlled Delegatecall Destination",
    "delegatecall-loop": "Delegatecall in Loop",
    "incorrect-exp": "Incorrect Exponentiation Operation",
    "incorrect-return": "Improper Return in Assembly",
    "msg-value-loop": "ETH Value Access in Loop",
    "reentrancy-eth": "Ether Theft via Reentrancy",
    "return-leave": "Incorrect Function Exit in Assembly",
    "storage-array": "Signed Integer Array Vulnerability",
    "unchecked-transfer": "Unchecked Token Transfer",
    "weak-prng": "Weak Random Number Generation",
    "domain-separator-collision": "EIP-2612 Domain Separator Collision",
    "enum-conversion": "Unsafe Enum Conversion",
    "erc20-interface": "Non-Standard ERC20 Implementation",
    "erc721-interface": "Non-Standard ERC721 Implementation",
    "incorrect-equality": "Risky Strict Equality Check",
    "locked-ether": "Permanently Locked Ether",
    "mapping-deletion": "Incomplete Mapping Deletion",
    "shadowing-abstract": "Abstract Contract Variable Shadowing",
    "tautological-compare": "Self-Comparison Issue",
    "tautology": "Always True/False Condition",
    "write-after-write": "Redundant State Variable Write",
    "boolean-cst": "Boolean Constant Misuse",
    "constant-function-asm": "State-Changing Constant Function (Assembly)",
    "constant-function-state": "State-Changing Constant Function",
    "divide-before-multiply": "Precision Loss in Arithmetic",
    "out-of-order-retryable": "Out-of-Order Retryable Transaction",
    "reentrancy-no-eth": "Reentrancy Vulnerability (No Ether Theft)",
    "reused-constructor": "Reused Base Constructor",
    "tx-origin": "Unsafe Transaction Origin Usage",
    "unchecked-lowlevel": "Unchecked Low-Level Call",
    "unchecked-send": "Unchecked Ether Sending",
    "uninitialized-local": "Uninitialized Local Variable",
    "unused-return": "Ignored Return Value",
    "incorrect-modifier": "Incorrect Modifier Implementation",
    "shadowing-builtin": "Built-in Symbol Shadowing",
    "shadowing-local": "Local Variable Shadowing",
    "uninitialized-fptr-cst": "Uninitialized Function Pointer in Constructor",
    "variable-scope": "Incorrect Variable Scope Usage",
    "void-cst": "Missing Constructor Implementation",
    "calls-loop": "Multiple External Calls in Loop",
    "events-access": "Missing Event for Critical Operation",
    "events-maths": "Missing Event for Arithmetic Operation",
    "incorrect-unary": "Dangerous Unary Expression",
    "missing-zero-check": "Missing Zero Address Check",
    "reentrancy-benign": "Benign Reentrancy Vulnerability",
    "reentrancy-events": "Event Ordering Vulnerability",
    "return-bomb": "Unexpected Gas Consumption in External Call",
    "timestamp": "Unsafe Timestamp Usage",
    "assembly": "Low-Level Assembly Usage",
    "assert-state-change": "State Change in Assert Statement",
    "boolean-equal": "Unnecessary Boolean Comparison",
    "cyclomatic-complexity": "High Function Complexity",
    "deprecated-standards": "Usage of Deprecated Solidity Features",
    "erc20-indexed": "Non-Indexed ERC20 Event Parameter",
    "function-init-state": "Function Initializing State Variable",
    "incorrect-using-for": "Incorrect Library Usage",
    "low-level-calls": "Low-Level Call Usage",
    "missing-inheritance": "Missing Contract Inheritance",
    "naming-convention": "Non-Standard Naming Convention",
    "pragma": "Inconsistent Solidity Version",
    "redundant-statements": "Redundant Code",
    "solc-version": "Outdated Solidity Version",
    "unimplemented-functions": "Unimplemented Function",
    "unused-import": "Unused Import",
    "unused-state": "Unused State Variable",
    "costly-loop": "Expensive Operation in Loop",
    "dead-code": "Unused Function",
    "reentrancy-unlimited-gas": "Potential Reentrancy with Unlimited Gas",
    "too-many-digits": "Non-Standard Number Notation",
    "cache-array-length": "Inefficient Array Length Usage in Loop",
    "constable-states": "Non-Constant State Variable",
    "external-function": "Non-External Public Function",
    "immutable-states": "Non-Immutable State Variable",
    "var-read-using-this": "Unnecessary 'this' Usage",
}
