import os
import re
import shutil
from typing import List

import toml

from api.v1.common.project_helpers import copy_solidity_files
from config.solidity_settings import FORGE_INIT_COMMAND, FORGE_REMAP_COMMAND
from core.utils.logger import logger
from core.utils.run_command import run_command


async def initialize_foundry_project(temp_dir: str, repo_dir: str, project_type: str) -> None:
    """
    Initializes a Foundry project by creating necessary directories and files.

    Args:
        temp_dir (str): The temporary directory path.
    """
    commands = [
        ["git", "init"],
        FORGE_INIT_COMMAND,
    ]
    for command in commands:
        returncode, _, stderr = await run_command(command, temp_dir)
        if returncode != 0:
            raise ValueError(f"Failed to initialize Foundry project: {stderr}")

    _clean_unused_files(temp_dir)

    foundry_src_dir = os.path.join(temp_dir, "src")
    copy_solidity_files(repo_dir, foundry_src_dir, project_type)
    _preprocess_solidity_files(temp_dir)


async def install_npm_deps(temp_dir: str, repo_dir: str) -> None:
    """
    Installs NPM dependencies in the specified directory.

    Args:
        temp_dir (str): The temporary directory where the dependencies should be installed.
        repo_dir (str): The directory of the Hardhat project.
    """
    # Copy package.json and package-lock.json from Hardhat project to Foundry project
    for file_name in ["package.json", "package-lock.json"]:
        src_file = os.path.join(repo_dir, file_name)
        dst_file = os.path.join(temp_dir, file_name)
        if os.path.exists(src_file):
            shutil.copy2(src_file, dst_file)

    # Install NPM dependencies in the Foundry project
    try:
        logger.info("Installing NPM dependencies...")
        returncode, _, stderr = await run_command(["npm", "install"], temp_dir)
        if returncode != 0:
            if "ERESOLVE" in stderr:
                logger.warning(
                    "NPM install failed due to dependency conflict. Retrying with --legacy-peer-deps."
                )
                returncode, _, stderr = await run_command(
                    ["npm", "install", "--legacy-peer-deps"], temp_dir
                )
                if returncode != 0:
                    logger.error(f"NPM install failed: {stderr}")
                    raise ValueError(f"NPM install failed: {stderr}")
            else:
                logger.error(f"NPM install failed: {stderr}")
                raise ValueError(f"NPM install failed: {stderr}")
        else:
            logger.info("NPM dependencies installed successfully.")
    except Exception as e:
        logger.exception(f"Error installing NPM dependencies: {str(e)}")
        raise


def _clean_unused_files(temp_dir: str) -> None:
    """
    Cleans up unused files in specified folders within the temporary directory.

    Args:
        temp_dir (str): The temporary directory path.
    """
    for folder in ["src", "script", "test"]:
        folder_path = os.path.join(temp_dir, folder)
        if os.path.exists(folder_path):
            for item in os.listdir(folder_path):
                item_path = os.path.join(folder_path, item)
                if os.path.isfile(item_path):
                    os.unlink(item_path)
                elif os.path.isdir(item_path):
                    shutil.rmtree(item_path)


async def generate_remappings_with_foundry(temp_dir: str) -> List[str]:
    """
    Generates remappings using Foundry's 'forge remappings' command and writes them to remappings.txt.

    Args:
        temp_dir (str): The temporary directory where the project is located.

    Returns:
        List[str]: A list of remapping strings.
    """
    returncode, stdout, stderr = await run_command(FORGE_REMAP_COMMAND, cwd=temp_dir)
    if returncode != 0:
        # logger.error(f"Failed to generate remappings with Foundry: {stderr}")
        raise ValueError(f"Failed to generate remappings with Foundry: {stderr}")

    remappings = stdout.strip().splitlines()
    if not remappings:
        raise ValueError("No remappings were generated by Foundry.")

    logger.info(f"Remappings generated: {remappings}")

    # Write remappings to file
    await _write_remappings(temp_dir, remappings)
    return remappings


async def _write_remappings(temp_dir: str, remappings: List[str]) -> None:
    """
    Writes remappings to the `remappings.txt` file in the temporary directory.

    Args:
        temp_dir (str): The temporary directory path.
        remappings (List[str]): A list of remapping strings.
    """
    remappings_path = os.path.join(temp_dir, "remappings.txt")
    with open(remappings_path, "w", encoding="utf-8") as f:
        f.write("\n".join(remappings))


def _preprocess_solidity_files(temp_dir: str) -> None:
    """
    Preprocesses Solidity files by replacing certain placeholders.

    Args:
        temp_dir (str): The temporary directory path.
    """
    src_dir = os.path.join(temp_dir, "src")
    for root, _, files in os.walk(src_dir):
        for file in files:
            if file.endswith(".sol"):
                file_path = os.path.join(root, file)
                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read()

                # Replace address variables assigned to empty strings
                content = re.sub(
                    r"address\s+(?:public|private|internal|external)?\s*(?:constant\s*)?\w+\s*=\s*\"\";",
                    lambda m: m.group().replace('""', "address(0)"),
                    content,
                )

                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(content)


def update_foundry_config(temp_dir: str) -> None:
    """
    Updates the `foundry.toml` configuration file with necessary settings.

    Args:
        temp_dir (str): The temporary directory path.

    Raises:
        FileNotFoundError: If the `foundry.toml` file is not found in the project directory.
    """
    logger.info("Updating foundry.toml configuration...")
    foundry_toml_path = os.path.join(temp_dir, "foundry.toml")
    if not os.path.exists(foundry_toml_path):
        raise FileNotFoundError("foundry.toml not found in the project directory.")

    with open(foundry_toml_path, "r", encoding="utf-8") as f:
        config = toml.load(f)

    # Ensure the default profile exists
    config.setdefault("profile", {})
    config["profile"].setdefault("default", {})

    # Set 'solc' to 'auto' instead of 'solc_version'
    config["profile"]["default"]["auto_detect_solc"] = True

    # Add 'node_modules' to the 'libs' array
    libs = config["profile"]["default"].get("libs", [])
    if "lib" not in libs:
        libs.append("lib")
    if "node_modules" not in libs:
        libs.append("node_modules")
    config["profile"]["default"]["libs"] = libs

    # Add fuzz settings
    config["profile"]["default"]["fuzz"] = {
        "runs": 1000,
        "max_test_rejects": 65536,
        "seed": "0x1",
        "dictionary_weight": 40,
        "include_storage": True,
        "include_push_bytes": True,
        "extra_output": ["storageLayout", "metadata"],
    }

    # Add invariant settings
    config["profile"]["default"]["invariant"] = {"runs": 256, "depth": 32, "fail_on_revert": True}

    with open(foundry_toml_path, "w", encoding="utf-8") as f:
        toml.dump(config, f)


def read_file(path: str) -> str:
    """
    Reads the content of a file.

    Args:
        path (str): The file path.

    Returns:
        str: The content of the file.
    """
    try:
        with open(path, "r", encoding="utf-8") as file:
            content = file.read()
        return content
    except Exception as e:
        logger.exception(f"Error reading file {path}: {str(e)}")
        raise
